### ISSUE TITLE
How/where to bring up issues and edit gitbook guidlines

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan.book#6]
@ashiklom and @bcow brought up a necessary delineation we need to have between content and gitbook development issues. Also, @dlebauer latest pull request brought up the point that we need a clear guideline for editing. 

The discussion section on gitbook itself will be where the public is pointed to if they would like to request changes to content. Gitbook development issues, brought up by the team, will be through Github issues. For editing, the usual git protocol (fork, clone, edit, push, pull request) will be advised to everyone that wants to make changes to this repository.

**Comment by mdietze** [comment]
Yes, and overall we need to make it very clear that we actively encourage feedback and contributions. We need to not be too dogmatic because constructive feedback from any channel is better than not getting feedback because the method for doing so is unintuitive or off-putting in it's formality

**Comment by tonygardella** [comment]
I added a "How to use this book" page to outline the structure and make it clear that we want the reader's feedback.

**Comment by dlebauer** [comment]
@tonygardella I don't see the "How to use this page" part of the book. 

But I agree with Mike that it should be as easy as possible with many options: send an email, gitter, chat, new issue, or pull request. 

Ideally people could easily edit and / or comment on GitBook too. 

#### A few other methods: 

##### Edit this page link

If anyone is feeling ambitious, I added this to the footer of my website (terraref.ncsa.illinois.edu) that provides a pencil icon that redirects to the home page. It would probably be better if people could figure out that it means 'edit this page' without having to hover. 

The code looks like:

`<a href="{{site.github.repository_url}}/edit/master/{{ page.path }}" title="Edit this page"><i class="fa fa-pencil-square-o fa-2x"></i></a>`

Not sure how to set the `site.github.repository_url` variable though:

##### GitBook Desktop

It would be ideal if GitBook had the ability to fork and submit pull requests. The GitBook desktop app does allow branching, and if it were used directly on the GitHub repo this could make it easier to use.

**Comment by tonygardella** [comment]
@dlebauer  I made a pull request for my edits. I'm going to stick to making pull requests and leave it up for a day or two for feedback before merging.

**Comment by dlebauer** [comment]
OK. Got it. I'll close this and move the comments above to #7
